<?php
register_block_pattern(
	'villela-barbearia/products',
	array(
		'title'       => __( 'Produtos e serviços', 'villela-barbearia' ),
		'description' => __( 'Seção com produtos premium da barbearia.', 'villela-barbearia' ),
		'categories'  => array( 'featured' ),
		'content'     => <<<'HTML'
<!-- wp:group {"align":"full","className":"brv-section brv-products","anchor":"products"} -->
<div class="wp-block-group alignfull brv-section brv-products" id="products">
	<!-- wp:group {"className":"brv-container brv-section__inner"} -->
	<div class="wp-block-group brv-container brv-section__inner">
		<!-- wp:group {"className":"brv-section__header"} -->
		<div class="wp-block-group brv-section__header"><!-- wp:paragraph {"className":"brv-section__badge"} --><p class="brv-section__badge">PERFUMARIA MASCULINA - ROGER VILELA</p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"brv-section__title"} --><h2 class="wp-block-heading brv-section__title">Produtos Premium Selecionados</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-section__description"} --><p class="brv-section__description">Os melhores produtos para elevar seus cuidados em casa, com qualidade profissional e o mesmo padrão que a Roger Vilela entrega no atendimento.</p><!-- /wp:paragraph --></div>
		<!-- /wp:group -->
		<!-- wp:group {"className":"brv-products__grid"} -->
		<div class="wp-block-group brv-products__grid">
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card" data-product-id="matte-styling-cream" data-category="CABELO" data-name="MATTE STYLING - CREAM" data-price="109.90"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/WhatsApp-Image-2026-07-29-at-18.11.01.jpeg" alt="Pote de pomada modeladora premium" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">CABELO</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">MATTE STYLING - CREAM</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Controle preciso com acabamento natural, leve e duradouro. Ideal para quem deseja estrutura sem excesso de brilho.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 109,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card" data-product-id="leave-in" data-category="CABELO" data-name="LEAVE-IN" data-price="109.90"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/WhatsApp-Image-2026-07-29-at-18.11.01.jpeg" alt="Leave-in hidratante multifuncional" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">CABELO</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">LEAVE-IN</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Hidratação profunda, proteção e sensação de leveza para o couro cabeludo e os fios. Perfeito para uso diário.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 109,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card" data-product-id="pomada-em-po" data-category="CABELO" data-name="POMADA EM PÓ" data-price="109.90"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-13_24_48.png" alt="Pomada em pó para cabelo" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">CABELO</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">POMADA EM PÓ</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Volume, textura e controle sem pesar. Acabamento seco, leve e sofisticado para qualquer estilo.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 109,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card" data-product-id="balm-barba" data-category="BARBA" data-name="BALM BARBA" data-price="109.90"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-13_24_48.png" alt="Balm para barba" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">BARBA</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">BALM BARBA</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Hidratação intensa para barba e rosto, com maciez, controle e aroma premium. Ideal para uso diário.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 109,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card" data-product-id="shampoo-premium-barba" data-category="BARBA" data-name="SHAMPOO PREMIUM - PARA BARBA" data-price="109.90"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-13_16_13.png" alt="Shampoo premium para barba" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">BARBA</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">SHAMPOO PREMIUM - PARA BARBA</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Limpeza suave e eficiente, com hidratação e fragrância premium. A barba fica macia, fresca e bem cuidada.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 109,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
		</div>
		<!-- /wp:group -->
		<div class="brv-product-order" aria-live="polite">
			<p class="brv-product-order__notice">Pagamento antecipado via Pix ou cartão. Dinheiro somente na retirada.</p>
			<div class="brv-product-order__items">
				<p class="brv-product-order__empty">Nenhum produto selecionado.</p>
			</div>
			<div class="brv-product-order__summary">
				<span>Total</span>
				<strong>R$ 0,00</strong>
			</div>
			<button class="primary-button brv-product-order__cta" type="button" disabled>Finalizar pedido pelo WhatsApp</button>
		</div>
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->
HTML
	)
);
