<?php
register_block_pattern(
	'villela-barbearia/products',
	array(
		'title'       => __( 'Produtos e serviços', 'villela-barbearia' ),
		'description' => __( 'Seção com produtos premium da barbearia.', 'villela-barbearia' ),
		'categories'  => array( 'featured' ),
		'content'     => <<<'HTML'
<!-- wp:group {"align":"full","className":"brv-section brv-products","anchor":"products"} -->
<div class="wp-block-group alignfull brv-section brv-products" id="products">
	<!-- wp:group {"className":"brv-container brv-section__inner"} -->
	<div class="wp-block-group brv-container brv-section__inner">
		<!-- wp:group {"className":"brv-section__header"} -->
		<div class="wp-block-group brv-section__header"><!-- wp:paragraph {"className":"brv-section__badge"} --><p class="brv-section__badge">Nossa Loja</p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"brv-section__title"} --><h2 class="wp-block-heading brv-section__title">Produtos Premium Selecionados</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-section__description"} --><p class="brv-section__description">Os melhores produtos do mercado para você cuidar do seu visual em casa com qualidade profissional.</p><!-- /wp:paragraph --></div>
		<!-- /wp:group -->
		<!-- wp:group {"className":"brv-products__grid"} -->
		<div class="wp-block-group brv-products__grid">
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1542818279-04aa19d54f06?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHxoYWlyJTIwcG9tYWRlJTIwcHJvZHVjdHxlbnwxfHx8fDE3NzI3MzYzNzN8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Pote de pomada modeladora premium" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Cabelo</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Pomada Modeladora Premium</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Fixação forte com acabamento natural. Ideal para todos os tipos de cabelo.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 49,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1655394009794-df4f7cd8582a?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHxiZWFyZCUyMG9pbCUyMGJvdHRsZSUyMHByb2R1Y3R8ZW58MXx8fHwxNzcyNzM2NTI5fDA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Frasco de óleo para barba" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Barba</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Óleo para Barba</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Hidratação profunda e crescimento saudável. Fragrância marcante.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 39,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1638609927040-8a7e97cd9d6a?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaGF2aW5nJTIwY3JlYW0lMjBsdXh1cnl8ZW58MXx8fHwxNzcyNzM2NTI5fDA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Creme de barbear Luxury" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Barba</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Creme de Barbear Luxury</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Barbear suave e confortável. Proteção e hidratação máxima.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 44,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1640869116016-93c00ba94b28?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHxjb2xvZ25lJTIwcGVyZnVtZSUyMGJvdHRsZXxlbnwxfHx8fDE3NzI3MzY1MzB8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Frasco de colônia masculina" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Fragrância</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Colônia Masculina</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Fragrância sofisticada e duradoura. Notas amadeiradas.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 79,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1706087476924-6c0ae4839556?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHxiYXJiZXIlMjBzY2lzc29ycyUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NzI3MzY1Mjl8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Tesouras profissionais para barbeiro" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Ferramentas</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Kit Ferramentas Premium</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Tesouras profissionais de aço inoxidável. Qualidade excepcional.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 149,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1759142449398-89357aa1bb36?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHxiYXJiZXIlMjBzaG9wJTIwdmludGFnZSUyMHByb2R1Y3RzfGVufDF8fHx8MTc3MjczNjM3Mnww&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Produtos vintage da barbearia" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Coleção</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Produtos Vintage</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Coleção exclusiva de produtos clássicos com toque moderno.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 89,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
		</div>
		<!-- /wp:group -->
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->
HTML
	)
);
