<?php
register_block_pattern(
	'villela-barbearia/products',
	array(
		'title'       => __( 'Produtos e serviços', 'villela-barbearia' ),
		'description' => __( 'Seção com produtos premium da barbearia.', 'villela-barbearia' ),
		'categories'  => array( 'featured' ),
		'content'     => <<<'HTML'
<!-- wp:group {"align":"full","className":"brv-section brv-products","anchor":"products"} -->
<div class="wp-block-group alignfull brv-section brv-products" id="products">
	<!-- wp:group {"className":"brv-container brv-section__inner"} -->
	<div class="wp-block-group brv-container brv-section__inner">
		<!-- wp:group {"className":"brv-section__header"} -->
		<div class="wp-block-group brv-section__header"><!-- wp:paragraph {"className":"brv-section__badge"} --><p class="brv-section__badge">Nossa Loja</p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"brv-section__title"} --><h2 class="wp-block-heading brv-section__title">Produtos Premium Selecionados</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-section__description"} --><p class="brv-section__description">Os melhores produtos do mercado para você cuidar do seu visual em casa com qualidade profissional.</p><!-- /wp:paragraph --></div>
		<!-- /wp:group -->
		<!-- wp:group {"className":"brv-products__grid"} -->
		<div class="wp-block-group brv-products__grid">
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/WhatsApp-Image-2026-07-29-at-18.11.01.jpeg" alt="Pote de pomada modeladora premium" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Cabelo</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Pomada Modeladora Premium</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Fixação forte com acabamento natural. Ideal para todos os tipos de cabelo.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 49,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-13_24_48.png" alt="Frasco de óleo para barba" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Barba</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Óleo para Barba</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Hidratação profunda e crescimento saudável. Fragrância marcante.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 39,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-13_16_13.png" alt="Creme de barbear Luxury" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Barba</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Creme de Barbear Luxury</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Barbear suave e confortável. Proteção e hidratação máxima.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 44,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-13_14_56.png" alt="Frasco de colônia masculina" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Fragrância</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Colônia Masculina</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Fragrância sofisticada e duradoura. Notas amadeiradas.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 79,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-12_55_14.png" alt="Tesouras profissionais para barbeiro" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Ferramentas</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Kit Ferramentas Premium</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Tesouras profissionais de aço inoxidável. Qualidade excepcional.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 149,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-product-card"} -->
			<div class="wp-block-group brv-product-card"><!-- wp:group {"className":"brv-product-card__media"} --><div class="wp-block-group brv-product-card__media"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://trutech.shop/wp-content/uploads/2026/10/ChatGPT-Image-8-de-jul.-de-2026-12_41_11.png" alt="Produtos vintage da barbearia" /></figure><!-- /wp:image --><!-- wp:paragraph {"className":"brv-product-card__category"} --><p class="brv-product-card__category">Coleção</p><!-- /wp:paragraph --><div class="brv-product-card__shade" aria-hidden="true"></div></div><!-- /wp:group --><!-- wp:group {"className":"brv-product-card__body"} --><div class="wp-block-group brv-product-card__body"><!-- wp:paragraph {"className":"brv-product-card__stars"} --><p class="brv-product-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Produtos Vintage</h3><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-product-card__description"} --><p class="brv-product-card__description">Coleção exclusiva de produtos clássicos com toque moderno.</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-product-card__price"} --><p class="brv-product-card__price">R$ 89,90</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-product-card__controls"} --><div class="wp-block-group brv-product-card__controls"><!-- wp:buttons {"className":"brv-quantity"} --><div class="wp-block-buttons brv-quantity"><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__decrease"} --><div class="wp-block-button brv-quantity__decrease"><button class="wp-block-button__link wp-element-button" type="button">−</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__value"} --><div class="wp-block-button brv-quantity__value"><button class="wp-block-button__link wp-element-button" type="button">0</button></div><!-- /wp:button --><!-- wp:button {"tagName":"button","type":"button","className":"brv-quantity__increase"} --><div class="wp-block-button brv-quantity__increase"><button class="wp-block-button__link wp-element-button" type="button">+</button></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"tagName":"button","type":"button","className":"primary-button brv-product-card__add"} --><div class="wp-block-button primary-button brv-product-card__add"><button class="wp-block-button__link wp-element-button" type="button">Adicionar</button></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
		</div>
		<!-- /wp:group -->
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->
HTML
	)
);
