<?php
register_block_pattern(
	'villela-barbearia/testimonials',
	array(
		'title'       => __( 'Depoimentos', 'villela-barbearia' ),
		'description' => __( 'Seção de avaliações de clientes.', 'villela-barbearia' ),
		'categories'  => array( 'featured' ),
		'content'     => str_replace(
			array(
				'<p class="brv-testimonial-card__comment">"',
				'"</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} -->',
			),
			array(
				'<p class="brv-testimonial-card__comment">&#34;',
				'&#34;</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} -->',
			),
			<<<'HTML'
<!-- wp:group {"align":"full","className":"brv-section brv-testimonials","anchor":"testimonials"} -->
<div class="wp-block-group alignfull brv-section brv-testimonials" id="testimonials">
	<!-- wp:group {"className":"brv-container brv-section__inner"} -->
	<div class="wp-block-group brv-container brv-section__inner">
		<!-- wp:group {"className":"brv-section__header"} -->
		<div class="wp-block-group brv-section__header"><!-- wp:paragraph {"className":"brv-section__badge"} --><p class="brv-section__badge">Depoimentos</p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"brv-section__title"} --><h2 class="wp-block-heading brv-section__title">O Que Nossos Clientes Dizem</h2><!-- /wp:heading --><!-- wp:paragraph {"className":"brv-section__description"} --><p class="brv-section__description">A satisfação dos nossos clientes é nossa maior conquista. Veja o que eles têm a dizer.</p><!-- /wp:paragraph --></div>
		<!-- /wp:group -->
		<!-- wp:group {"className":"brv-testimonials__grid"} -->
		<div class="wp-block-group brv-testimonials__grid">
			<!-- wp:group {"className":"brv-testimonial-card"} -->
			<div class="wp-block-group brv-testimonial-card"><div class="brv-testimonial-card__quote" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 21c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2H4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Zm12 0c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2h-4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Z"/></svg></div><!-- wp:paragraph {"className":"brv-testimonial-card__stars"} --><p class="brv-testimonial-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-testimonial-card__comment"} --><p class="brv-testimonial-card__comment">"Melhor barbearia que já frequentei! O atendimento é impecável e o resultado sempre supera minhas expectativas. Carlos é um verdadeiro artista."</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} --><div class="wp-block-group brv-testimonial-card__author"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1763610452420-71b91bc59160?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGVnYW50JTIwbWFuJTIwaGFpcmN1dHxlbnwxfHx8fDE3NzI3MzYzNzJ8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Ricardo Almeida" /></figure><!-- /wp:image --><!-- wp:group {"layout":{"type":"default"}} --><div class="wp-block-group"><!-- wp:paragraph --><p>Ricardo Almeida</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Empresário</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-testimonial-card"} -->
			<div class="wp-block-group brv-testimonial-card"><div class="brv-testimonial-card__quote" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 21c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2H4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Zm12 0c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2h-4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Z"/></svg></div><!-- wp:paragraph {"className":"brv-testimonial-card__stars"} --><p class="brv-testimonial-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-testimonial-card__comment"} --><p class="brv-testimonial-card__comment">"Ambiente sofisticado e profissionais extremamente qualificados. O João faz um trabalho excepcional com barba. Recomendo de olhos fechados!"</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} --><div class="wp-block-group brv-testimonial-card__author"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1768363446104-b8a0c1716600?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJiZXIlMjBjdXR0aW5nJTIwaGFpciUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NzI3MzYzNzF8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Felipe Costa" /></figure><!-- /wp:image --><!-- wp:group {"layout":{"type":"default"}} --><div class="wp-block-group"><!-- wp:paragraph --><p>Felipe Costa</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Advogado</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-testimonial-card"} -->
			<div class="wp-block-group brv-testimonial-card"><div class="brv-testimonial-card__quote" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 21c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2H4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Zm12 0c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2h-4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Z"/></svg></div><!-- wp:paragraph {"className":"brv-testimonial-card__stars"} --><p class="brv-testimonial-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-testimonial-card__comment"} --><p class="brv-testimonial-card__comment">"A Villela é muito mais que uma barbearia, é uma experiência. Desde a recepção até o acabamento final, tudo é perfeito. Pedro é sensacional!"</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} --><div class="wp-block-group brv-testimonial-card__author"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1654097803253-d481b6751f29?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJiZXIlMjBiZWFyZCUyMHRyaW1taW5nfGVufDF8fHx8MTc3MjczNjM3Mnww&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Marcelo Santos" /></figure><!-- /wp:image --><!-- wp:group {"layout":{"type":"default"}} --><div class="wp-block-group"><!-- wp:paragraph --><p>Marcelo Santos</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Médico</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-testimonial-card"} -->
			<div class="wp-block-group brv-testimonial-card"><div class="brv-testimonial-card__quote" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 21c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2H4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Zm12 0c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2h-4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Z"/></svg></div><!-- wp:paragraph {"className":"brv-testimonial-card__stars"} --><p class="brv-testimonial-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-testimonial-card__comment"} --><p class="brv-testimonial-card__comment">"Qualidade premium em todos os aspectos. Produtos de primeira linha e profissionais que realmente entendem do que fazem. Virei cliente fiel!"</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} --><div class="wp-block-group brv-testimonial-card__author"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1747832512459-5566e6d0ee5a?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBiYXJiZXIlMjBwb3J0cmFpdHxlbnwxfHx8fDE3NzI3MTU1NTd8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="André Oliveira" /></figure><!-- /wp:image --><!-- wp:group {"layout":{"type":"default"}} --><div class="wp-block-group"><!-- wp:paragraph --><p>André Oliveira</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Arquiteto</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-testimonial-card"} -->
			<div class="wp-block-group brv-testimonial-card"><div class="brv-testimonial-card__quote" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 21c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2H4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Zm12 0c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2h-4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Z"/></svg></div><!-- wp:paragraph {"className":"brv-testimonial-card__stars"} --><p class="brv-testimonial-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-testimonial-card__comment"} --><p class="brv-testimonial-card__comment">"Atendimento cinco estrelas! O ambiente é super agradável e os barbeiros são muito atenciosos. Sempre saio de lá renovado e satisfeito."</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} --><div class="wp-block-group brv-testimonial-card__author"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1741345980697-f3c43eba44a0?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXJiZXIlMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMG1hbnxlbnwxfHx8fDE3NzI3MzY0NDB8MA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Gustavo Lima" /></figure><!-- /wp:image --><!-- wp:group {"layout":{"type":"default"}} --><div class="wp-block-group"><!-- wp:paragraph --><p>Gustavo Lima</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Engenheiro</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
			<!-- wp:group {"className":"brv-testimonial-card"} -->
			<div class="wp-block-group brv-testimonial-card"><div class="brv-testimonial-card__quote" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 21c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2H4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Zm12 0c3 0 7-1 7-8V5c0-1.25-.76-2.02-2-2h-4c-1.25 0-2 .75-2 1.97V11c0 1.25.75 2 2 2h1v1c0 1-1 2-2 2s-1 .01-1 1.03V20c0 1 0 1 1 1Z"/></svg></div><!-- wp:paragraph {"className":"brv-testimonial-card__stars"} --><p class="brv-testimonial-card__stars">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"brv-testimonial-card__comment"} --><p class="brv-testimonial-card__comment">"Simplesmente a melhor! Atenção aos detalhes, produtos premium e um ambiente que te faz sentir especial. Vale cada centavo!"</p><!-- /wp:paragraph --><!-- wp:group {"className":"brv-testimonial-card__author"} --><div class="wp-block-group brv-testimonial-card__author"><!-- wp:image {"sizeSlug":"full","linkDestination":"none"} --><figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1761931403671-d020a14928d9?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWxlJTIwaGFpcnN0eWxpc3QlMjBwcm9mZXNzaW9uYWx8ZW58MXx8fHwxNzcyNzM2NDM5fDA&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=1080" alt="Bruno Ferreira" /></figure><!-- /wp:image --><!-- wp:group {"layout":{"type":"default"}} --><div class="wp-block-group"><!-- wp:paragraph --><p>Bruno Ferreira</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Designer</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div>
			<!-- /wp:group -->
		</div>
		<!-- /wp:group -->
		<!-- wp:group {"className":"brv-testimonials__stats"} -->
		<div class="wp-block-group brv-testimonials__stats"><!-- wp:group {"className":"brv-testimonials__stat"} --><div class="wp-block-group brv-testimonials__stat"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">5000+</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Clientes Satisfeitos</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"brv-testimonials__stat"} --><div class="wp-block-group brv-testimonials__stat"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">4.9</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Avaliação Média</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"brv-testimonials__stat"} --><div class="wp-block-group brv-testimonials__stat"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">98%</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Recomendação</p><!-- /wp:paragraph --></div><!-- /wp:group --></div>
		<!-- /wp:group -->
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->
HTML
		),
	)
);
